# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01dd6a93a33636d1c214a431caa57cef336a59de30a0daae68fdb79012fa1372415e783afe4ce90afe83f6582028db26505a6715f03599d4655a1be67731221c

test:
  secret_key_base: 4a72b4d706f6225fe92e41ccb5a5587b29ef29d25d3e212063ced33c2d89d04201e246c9a6f2798785b617a85cbdda155bc3329ca20c435f00590b986b2356d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
